site_name: Linkboy
site_url: https://www.pixelrespawn.com

nav:
  - index.md
  - using-linkboy.md
  - privacy-policy.md
  - contact.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  logo: images/linkboy-icon.png
  palette:
    primary: custom

copyright: Copyright &copy; 2024-2025 Pixel Respawn LLC

extra_css:
  - stylesheets/extra.css
