site_name: Linkboy
site_url: https://www.pixelrespawn.com

nav:
  - index.md
  - privacy-policy.md
  - contact.md

theme:
  name: material
  logo: images/linkboy-icon.png
  palette:
    primary: custom

copyright: Copyright &copy; 2024-2025 Pixel Respawn LLC

extra_css:
  - stylesheets/extra.css
